services:
  # The Web Player (Frontend + Backend)
  - type: web
    name: vavoo-iptv-player
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT python_iptv.server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    autoDeploy: true
